### ISSUE TITLE
API: Add comment table to store comments for posts. Implement create comment endpoint

### ISSUE THREAD

**Issue by George-Alexander-S** [boolean-uk/team-dev-server-ex-2410-team1#29]
**Description**
CreateComment: creates a comment linked to a postId, including the logged in user.

**Table contents:**
```
id (int, primary key)
content (text)
postId (int foreign key)
createdAt (DateTime)
updatedAt (DateTime)
authorId (int, foreign key)
```

**Endpoint**
```
POST /posts/{id}/comments
```
RESPONSE:
**->status**

201 Created

**->object:**
```
{
"status": "string",
"data": {
    "comment": {
    "id": 0,
    "content": "string",
    "postId": int,
    "createdAt": "string", "datetime",
    "updatedAt": "string", "datetime",
    "author": {
        "id": 0,
        "cohortId": 0,
        "role": "string",
        "firstName": "string",
        "lastName": "string",
        "bio": "string",
        "githubUrl": "string",
        "profileImageUrl": "string"
                }
            }
        }
    }
```
400 Bad Request
{
"status": "error"
"message": "content cannot be empty"

}

401 unauthorized 

{
"status": "error"
"message": "User must be logged in for creating a comment" 
}

**Comment by dogezen** [comment]
Title is unclear: better something like "Add a table to store Comments for posts and implement create comment endpoint"

Missing:
a) what is the endpoint url going to be?
b) what properties are you going to include in the table? at least a reference to the post that is being commented on and a reference to the author of the comment
c) the postId should be integer, not string, I would imagine
d) are you going to store created at and updated at timestamps (see Prisma docs for easily adding these automatically, without need for user to provide them)

I think the endpoint should be something like: `POST /posts/:postId/comment` to indicate we are creating a comment against a specific post`. 

The author can be taken directly from the `req.user` since we assume you must be logged in to create a comment.

MISSING as well:
- 404 post not found
- 401 use not logged in
- 400 -> what are the bad requests? ie comment text is null/empty or missing? what else (if anything)?

**Comment by allendewilzin** [comment]
👍🏻 Looks good.
